Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPagesize: 10
  MaxPagesize: 100
  LogPath: log
  LogFilename: app
  LogFileExt: .log

# Database: # your db config
#   DBType: mysql
#   Username: # your username
#   Password: # your password
#   Host: # your host
