Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPagesize: 10
  MaxPagesize: 100
  LogPath: log
  LogFilename: app
  LogFileExt: .log
  UploadPath: static/upload
  UploadUrl: http://127.0.0.1:8000/static
  UploadMaxSizeImg: 5 # MB
  UploadMaxSizeExcel: 20
  UploadMaxSizeWord: 20
  UploadMaxSizePPT: 20
  UploadMaxSizeTxt: 20
  UploadExtsImg:
    - .jpg
    - .jpeg
    - .png
  UploadExtsExcel:
    - .xls
    - .xlsx
  UploadExtsWord:
    - .doc
    - .docx
  UploadExtsPPT:
    - .ppt
    - .pptx
  UploadExtsTxt:
    - .txt
  ContextTimeout: 60
JWT:
  Secret: bgobgobgo
  Issuer: bgo
  Expire: 30
RateLimiter:
  FillInterval: 1
  Capacity: 100
  Quantum: 100

# Database: # your db config
#   DBType: mysql
#   Username: # your username
#   Password: # your password
#   Host: # your host
